// flow-typed signature: d5b04c5a7e9138e13e4854c31990d184
// flow-typed version: <<STUB>>/apollo-boost_v^0.4.4/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-boost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-boost' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-boost/lib/bundle.cjs' {
  declare module.exports: any
}

declare module 'apollo-boost/lib/bundle.cjs.min' {
  declare module.exports: any
}

declare module 'apollo-boost/lib/bundle.esm' {
  declare module.exports: any
}

declare module 'apollo-boost/lib/bundle.umd' {
  declare module.exports: any
}

declare module 'apollo-boost/lib' {
  declare module.exports: any
}

// Filename aliases
declare module 'apollo-boost/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.cjs'>
}
declare module 'apollo-boost/lib/bundle.cjs.min.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.cjs.min'>
}
declare module 'apollo-boost/lib/bundle.esm.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.esm'>
}
declare module 'apollo-boost/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.umd'>
}
declare module 'apollo-boost/lib/index' {
  declare module.exports: $Exports<'apollo-boost/lib'>
}
declare module 'apollo-boost/lib/index.js' {
  declare module.exports: $Exports<'apollo-boost/lib'>
}
