// flow-typed signature: 024073d9befa4141606990a442dfbcf8
// flow-typed version: <<STUB>>/eslint-plugin-jest-dom_v^2.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest-dom' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest-dom/build/generate-readme-table' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/jest.config' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/createBannedAttributeRule' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-checked' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-empty' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-enabled-disabled' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-focus' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-required' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/lib/rules/prefer-to-have-attribute' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/fixtures/createBannedAttributeTestCases' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/index.test' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/lib/rules/no-attribute-checking' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-empty' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-focus' {
  declare module.exports: any
}

declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-to-have-attribute' {
  declare module.exports: any
}

// Filename aliases
declare module 'eslint-plugin-jest-dom/build/generate-readme-table.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/build/generate-readme-table'>
}
declare module 'eslint-plugin-jest-dom/jest.config.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/jest.config'>
}
declare module 'eslint-plugin-jest-dom/lib/createBannedAttributeRule.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/createBannedAttributeRule'>
}
declare module 'eslint-plugin-jest-dom/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib'>
}
declare module 'eslint-plugin-jest-dom/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-checked.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-checked'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-empty.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-empty'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-enabled-disabled.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-enabled-disabled'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-focus'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-required.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-required'>
}
declare module 'eslint-plugin-jest-dom/lib/rules/prefer-to-have-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/lib/rules/prefer-to-have-attribute'>
}
declare module 'eslint-plugin-jest-dom/tests/fixtures/createBannedAttributeTestCases.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jest-dom/tests/fixtures/createBannedAttributeTestCases',
  >
}
declare module 'eslint-plugin-jest-dom/tests/index.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/tests/index.test'>
}
declare module 'eslint-plugin-jest-dom/tests/lib/rules/no-attribute-checking.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/tests/lib/rules/no-attribute-checking'>
}
declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-empty.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/tests/lib/rules/prefer-empty'>
}
declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jest-dom/tests/lib/rules/prefer-focus'>
}
declare module 'eslint-plugin-jest-dom/tests/lib/rules/prefer-to-have-attribute.js' {
  declare module.exports: $Exports<
    'eslint-plugin-jest-dom/tests/lib/rules/prefer-to-have-attribute',
  >
}
